AV JSON Importer
OTRI-Unipd/OTRI pull request #2
Opened 2020-04-15 21:46 UTC by RicDeZen

### Alpha Vantage Importer
Added an Importer for Alpha Vantage:
- Takes the datetime keys and inserts them in each atom
- Inserts the metadata in each atom
- Inserts the atom array in the database

### JSON key handler
Just a module containing a script that can apply recursively any kind of function to all the keys in a json dictionary, as deep as possible.
Also contains premade methods to rename keys and turn them into lower case.

2020-04-18 13:10 UTC, CremaLuca requested changes
Could you use `json_key_handler` on YahooJSONDataImporter too please?

2020-04-18 13:10 UTC, CremaLuca commented on importer/av_json_data_importer.py
> +    def _add_timestamp(self, data_dict: dict):
Is this method private? Doesn't private methods require two underscores?

https://www.geeksforgeeks.org/private-methods-in-python/

2020-04-18 13:10 UTC, CremaLuca commented on importer/av_json_data_importer.py
> +        Adds each metadata field to all dictionary elements of the given list
A little confusing, try:
"Adds each metadata field to all ~dictionary~ atoms of the given list"

2020-04-18 13:10 UTC, CremaLuca commented on importer/av_json_data_importer.py
> +        Copies the timestamp key inside each atom.
```suggestion
        Copies the timestamp key inside each atom as a dictionary entry.
```

2020-04-18 13:55 UTC, RicDeZen commented on importer/av_json_data_importer.py
> +    def _add_timestamp(self, data_dict: dict):
My bad, not sure where but I somehow got the idea they needed only one will fix it

2020-04-18 13:57 UTC, RicDeZen commented
> 
> 
> Could you use `json_key_handler` on YahooJSONDataImporter too please?

Omw
https://tenor.com/view/yosha-vegito-vegito-blue-leggito-running-gif-16419170

2020-04-20 19:24 UTC, CremaLuca approved these changes
Seems all ok now. GJ
![OK](https://media1.giphy.com/media/kRXnZwKrPTwVq/200.webp?cid=ecf05e4728f2a60059608a8525c5f4f5e255d64737559ad6&rid=200.webp)

2020-04-21 20:41 UTC, merged